RANDOMNESS:
  torch_seed: 0
  numpy_seed: 0

DATASET_PARAMS:
  db_name: "snowed" # options: swed or snowed
  db_path: "data/SNOWED_v02/SNOWED" # dataset path
  bands: "rgb" # options: rgb, color_ir or ndwi
  use_copypaste_aug: true
  probability_of_aug: 0.5

TRAIN_PARAMS:
  num_epochs: 100
  batch_size: 32
  num_workers: 8
  lr: 0.00005

MODEL_PARAMS:
  model_config: "b0" # b0-5

OUTPUT_PATH:
  weights_path: "weights"
  model_name: "b0_rgb.pth"
  inference_path: "outputs"  
